version: "3.9"

services:
  wg_classic:
    build: { context: ./permutations/wg_classic }
    image: wg_classic:local
    container_name: wg_classic
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data

  wg_hybrid:
    build: { context: ./permutations/wg_hybrid }
    image: wg_hybrid:local
    container_name: wg_hybrid
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data

  wg_pqc:
    build: { context: ./permutations/wg_pqc }
    image: wg_pqc:local
    container_name: wg_pqc
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data

  ipsec_pqc:
    build: { context: ./permutations/ipsec_pqc }
    image: ipsec_pqc:local
    container_name: ipsec_pqc
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data

  ovpn_classic:
    build: { context: ./permutations/ovpn_classic }
    image: ovpn_classic:local
    container_name: ovpn_classic
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data

  ovpn_hybrid:
    build: { context: ./permutations/ovpn_hybrid }
    image: ovpn_hybrid:local
    container_name: ovpn_hybrid
    privileged: true
    network_mode: host
    env_file: [.env]
    volumes:
      - ./scripts:/scripts:ro
      - ./bench:/bench
      - /data:/data
